---

- name: Setup DNS records within zone
  community.dns.hetzner_dns_record:
    hetzner_api_token: "{{ hetzner_dnsapi_token }}"
    zone_name: "{{ hetzner_zone_name }}"
    prefix: "{{ record.prefix | default(omit) }}"
    record: "{{ record.name | default(omit) }}"
    type: "{{ record.type }}"
    ttl: "{{ record.ttl | default(omit) }}"
    value: "{{ record.value }}"
    state: "{{ record.state | default('present') }}"
  loop: "{{ hetzner_dns_records }}"
  loop_control:
    loop_var: record
