---

- name: Setup DNS records within zone
  community.dns.hetzner_dns_record:
    api_token: "{{ hetzner_dnsapi_token }}"
    zone_name: "{{ hetzner_zone_name }}"
    prefix: "{{ item.prefix | default(omit) }}"
    record: "{{ item.name | default(omit) }}"
    type: "{{ item.type }}"
    ttl: "{{ item.ttl | default(omit) }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ hetzner_dns_records }}"
